### ISSUE TITLE
Lets create gophp72

### ISSUE THREAD

**Issue by vv12131415** [TomasVotruba/gophp71.org#33]
Are you interested in creating https://gophp72.org ?
Because php7.1 is not supported now

My idea is get top 1000 packages for packagist and check if the latest release requeres 7.2 or above, if it does then show it on the list in one color, otherwise in other color

**Comment by TomasVotruba** [comment]
Hi, why would you aim at PHP 7.2 and not 7.3 or 7.4?

**Comment by vv12131415** [comment]
because 7.1 is currently dead, so the 7.2 is least accessible

**Comment by TomasVotruba** [comment]
That would be too weak argument for me to migrate all PHP packages to PHP 7.2.

GoPHP 7.1 was not chosen just because 7.0 was not-supported. It was still supported in those times actually.

Reasons made sense to community as whole, see: https://www.tomasvotruba.cz/blog/2017/06/05/go-php-71/#why-go-right-to-php-7-1

**Comment by vv12131415** [comment]
@TomasVotruba sooo... I will just close this issue?

**Comment by TomasVotruba** [comment]
You can.
